### ISSUE TITLE
Could not parse kubeconfig file - keyNotFound

### ISSUE THREAD

**Issue by voigt** [turkenh/KubeContext#1]
Hi,

first of all great idea! :)

However, after installing and configuring the kubeconfig file I get the following error message:

```
Could not parse selected kubeconfig file
 keyNotFound(CodingKeys(stringValue: "env", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "users", intValue: nil), _YAMLCodingKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "exec", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"env\", intValue: nil) (\"env\").", underlyingError: nil))
```

Here the config file:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <cert>
    server: https://<id>.sk1.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:<account-id>:cluster/test2-blub
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:<account-id>:cluster/test2-blub
    user: arn:aws:eks:us-east-1:<account-id>:cluster/test2-blub
  name: arn:aws:eks:us-east-1:<account-id>:cluster/test2-blub
current-context: arn:aws:eks:us-east-1:<account-id>:cluster/test2-blub
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:<account-id>:cluster/test2-blub
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - test2-blub
      command: aws-iam-authenticator
```

In case this is relevant: the config file is generated by `aws eks update-kubeconfig --name`.
Any idea how to fix this? :)
