### ISSUE TITLE
Feature Request: Handling multiple config files

### ISSUE THREAD

**Issue by 5nafu** [turkenh/KubeContext#19]
Hi turkenh,

your tool looks quite cool, but unfortunately I do have multiple `kubeconfig` files that I would like to use.
Basically I split the config files by customer, and merging them together would make them quite messy.

On the commandline, I can use the `KUBECONFIG` environment variable to merge these files and they work fine with kubectl, kubectx, lens,... 

my directory structure (`~/.kube/config.d` in my case) would look like:

```bash
$ ls -1
00_preferences
customer_1
customer_2
customer_3
private_cluster
```

The preferences file is basically being used to hold the current context and global preferences, the other files look like normal kubeconfig files:

```yaml
apiVersion: v1
kind: Config
contexts:
- name: customer1-develop
  context:
    cluster: customer1-develop
    user: 5nafu@customer1
- name: customer1-production
  context:
    cluster: customer1-production
    user: 5nafu@customer1
- name: test@customer1-develop
  context:
    cluster: customer1-develop
    user: test@customer1

clusters:
- name: customer1-develop
  cluster:
    server: https://<URL redacted>
- name: customer_1-production
  cluster:
    server: https://<URL redacted>

users:
- name: 5nafu@customer1
  user:
    token: <TOKEN redacted>
- name: test@customer1
  user:
    token: <TOKEN redacted>
```

It would be great if `KubeContext` could support this kind of multiple files structure.
