### ISSUE TITLE
bug: fails with teleport clusters

### ISSUE THREAD

**Issue by jithintm** [turkenh/KubeContext#22]
getting the following error on setting the kubeconfig:
```yaml
Could not parse selected kubeconfig file
typeMismatch(Yams.Node.Mapping, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "contexts", intValue: nil), _YAMLCodingKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "context", intValue: nil), CodingKeys(stringValue: "extensions", intValue: nil), _YAMLCodingKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "extension", intValue: nil)], debugDescription: "Expected to decode Mapping but found Node instead.", underlyingError: nil))
```

Similar to #12 but with a different kubeconfig for me:
```yaml
- context:
    cluster: teleport.<cluster>.com
    extensions:
    - extension: us-east1
      name: teleport.kube.name
    namespace: jim
    user: teleport.<cluster>.com-user
  name: teleport.<cluster>.com-user
- context:
    cluster: teleport.<cluster2>.com
    extensions:
    - extension: sa-west1
      name: teleport.kube.name
    namespace: jim
    user: teleport.<cluster2>.com-user
  name: teleport.<cluster2>.com-user
```

P.S.:  redacted irrelevant stuff.

note that `extensions.extension` is a string in my case.
