### ISSUE TITLE
Could not parse selected kubeconfig file - typeMismatch

### ISSUE THREAD

**Issue by adamdodev** [turkenh/KubeContext#3]
Version `1.05` from the App Store

When selecting the kubeconfig file:

```
Could not parse selected kubeconfig file
 typeMismatch(Yams.Node.Sequence, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "users", intValue: nil), _YAMLCodingKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "exec", intValue: nil), CodingKeys(stringValue: "env", intValue: nil)], debugDescription: "Expected to decode Sequence but found Node instead.", underlyingError: nil))
```

kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: snipped-cert
    server: redacted-url
  name: dev-cluster
- cluster:
    certificate-authority-data: snipped-cert
    server: redacted-url
  name: prod-cluster
contexts:
- context:
    cluster: dev-cluster
    user: dev-user
  name: dev
- context:
    cluster: prod-cluster
    user: prod-user
  name: prod
current-context: dev
kind: Config
preferences: {}
users:
- name: dev-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - redacted-url
      - -r
      - redacted-arn
      command: aws-iam-authenticator
      env: null
- name: prod-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - redacted-url
      - -r
      - redacted-arn
      command: aws-iam-authenticator
      env: null
```

**Comment by turkenh** [comment]
This is caused by the following line:

`env: null`

As a quick solution, you can simply delete that line(s)(2 occurrences), since not having that field should have the same meaning as having as "null".

I'll investigate further.

**Comment by adamdodev** [comment]
Great stuff, thank you!

**Comment by so-jelly** [comment]
I am experiencing this with AWS clusters.   They keep auto adding to the file so removing is not working well for me.   GKE clusters don't seem to be adding this field.

**Comment by scottrbaxter** [comment]
I am also experiencing this issue. Confirmed, i can remove the `env: null` line and it works immediately (doesn't even need app restart), but AWS EKS will update this file, so I'm still looking for a long-term solution.

**Comment by turkenh** [comment]
Fix is included in [v1.23](https://github.com/turkenh/KubeContext/releases/tag/v1.23)

**Comment by turkenh** [comment]
v1.23 is available on brew as well.

**Comment by ltagliamonte-dd** [comment]
Hello @turkenh i'm experiencing the same issue on latest release:
```
Could not parse selected kubeconfig file
typeMismatch(Yams.Node.Sequence, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "users", intValue: nil)], debugDescription: "Expected to decode Sequence but found Node instead.", underlyingError: nil))
```

this is my config:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tXXX
    server: https://api-main-00-staging-usXXX
    tls-server-name: api.internal.main-00.stagingXXX
  name: main-00.stagingXXX
contexts:
- context:
    cluster: main-00.stagingXXX
    user: ""
  name: main-00.stagingXXX
current-context: main-00.stagingXXX
kind: Config
preferences: {}
users: null

```
