### ISSUE TITLE
namespaces with numbers fail

### ISSUE THREAD

**Issue by mark-armstrong** [turkenh/KubeContext#9]
when namespaces are a number (e.g. "namespace":"973585995"), the quotes around the config are removed after changing contexts using KubeContext

#### kube config before using KubeContext
```yaml
contexts:
- context:
    cluster: somecluster
    namespace: "973585995"
    user: someuser
  name: somename
```
#### kube config after using KubeContext
```yaml
contexts:
- context:
    cluster: somecluster
    namespace: 973585995
    user: someuser
  name: somename
```

resulting in the following error:

`$ kubectl config get-contexts`
```
error: Error loading config file "/Users/mark/.kube/config": v1.Config.Contexts: []v1.NamedContext: v1.NamedContext.Context: v1.Context.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":973585995,"|..., bigger context ...|ext"},{"context":{"cluster":"somecluster","namespace":973585995,"user":"someuser"},"name":"somename"},{"c|...
```
